[DFR1195_base]
extends = esp32_base
board = dfr1195
board_check = true
board_build.mcu = esp32s3
build_flags =
  ${esp32_base.build_flags}
  -I variants/dfr1195
  -include variants/dfr1195/tft_spi.h
  -D DFR1195
  -D P_LORA_DIO_1=4
  -D P_LORA_NSS=10
  -D P_LORA_RESET=41
  -D P_LORA_BUSY=40
  -D P_LORA_SCLK=7
  -D P_LORA_MISO=5
  -D P_LORA_MOSI=6
  -D PIN_USER_BTN=18
  -D PIN_STATUS_LED=21
  -D PIN_VBAT_READ=1
  -D PIN_TFT_SDA=11
  -D PIN_TFT_SCL=12
  -D PIN_TFT_DC=14
  -D PIN_TFT_RST=15
  -D PIN_TFT_CS=17
  -D PIN_TFT_LEDA_CTL=16
  -D PIN_TFT_LEDA_CTL_ACTIVE=HIGH
  -D PIN_TFT_VDD_CTL=48
  -D PIN_TFT_VDD_CTL_ACTIVE=LOW
  -D USE_PIN_TFT=1
  -D ST7735_CUSTOM_INIT=1
  -D DISPLAY_ROTATION=3
  -D ST7735_INITR_PROFILE=INITR_MINI160x80
  -D ST7735_SPI_HZ=10000000
  -D ST7735S_R80x160_IC_WIDTH=80
  -D ST7735S_R80x160_IC_HEIGHT=160
  -D ST7735S_COLSET=0x2A
  -D ST7735S_RAWSET=0x2B
  -D ST7735S_RAMWR=0x2C
  -D ST7735S_MADCTL=0x36
  -D ST7735S_R80x160_MADCTL_RGB=0x08
  -D ST7735_FORCE_INVOFF=1
  -D ST7735_FORCE_COLMOD_565=1
  -D MULTI_CLICK_WINDOW_MS=120
  -D TFT_VDD_CONTROL=1
  -D BLE_SET_MIN_PREFERRED=1
  -D BLE_EARLY_LINK_CONNECTED=1
  -D BLE_LOG_AUTH_DETAILS=0
  -D USE_SX1262
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=22
  -D SX126X_DIO2_AS_RF_SWITCH=true
  -D SX126X_RXEN=42
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=0
  -D ESP32_CPU_FREQ=80
  -D RXPS_ENABLED=1
  -D UI_SHOW_UPTIME=1
build_src_filter =
  ${esp32_base.build_src_filter}
  +<../variants/dfr1195>
lib_deps =
  ${esp32_base.lib_deps}
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
  bodmer/TFT_eSPI @ ^2.4.31

[env:DFR1195_repeater]
extends = DFR1195_base
build_src_filter =
  ${DFR1195_base.build_src_filter}
  +<helpers/ui/ST7735Display.cpp>
  +<../examples/simple_repeater>
build_flags =
  ${DFR1195_base.build_flags}
  -D DISPLAY_CLASS=DFR1195Display
  -D ADVERT_NAME='"DFR1195 Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
lib_deps =
  ${DFR1195_base.lib_deps}
  ${esp32_ota.lib_deps}

[env:DFR1195_repeater_no_lcd]
extends = DFR1195_base
build_src_filter =
  ${DFR1195_base.build_src_filter}
  +<../examples/simple_repeater>
build_flags =
  ${DFR1195_base.build_flags}
  -D ADVERT_NAME='"DFR1195 Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
lib_deps =
  ${DFR1195_base.lib_deps}
  ${esp32_ota.lib_deps}

[env:DFR1195_companion_radio_ble]
extends = DFR1195_base
build_flags =
  ${DFR1195_base.build_flags}
  -I src/helpers/ui
  -I examples/companion_radio/ui-new
  -D DISPLAY_CLASS=DFR1195Display
  -D ENABLE_PRIVATE_KEY_IMPORT=1
  -D ENABLE_PRIVATE_KEY_EXPORT=1
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=654321
  -D BLE_DEBUG_LOGGING=0
  -D MESH_DEBUG=0
  -D OFFLINE_QUEUE_SIZE=256
  -D AUTO_SHUTDOWN_MILLIVOLTS=3000
build_src_filter =
  ${DFR1195_base.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<helpers/ui/ST7735Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${DFR1195_base.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:DFR1195_companion_radio_ble_no_lcd]
extends = DFR1195_base
build_flags =
  ${DFR1195_base.build_flags}
  -D ENABLE_PRIVATE_KEY_IMPORT=1
  -D ENABLE_PRIVATE_KEY_EXPORT=1
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=654321
  -D BLE_DEBUG_LOGGING=0
  -D MESH_DEBUG=0
  -D OFFLINE_QUEUE_SIZE=256
  -D AUTO_SHUTDOWN_MILLIVOLTS=3000
build_src_filter =
  ${DFR1195_base.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<../examples/companion_radio/*.cpp>
lib_deps =
  ${DFR1195_base.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:DFR1195_companion_radio_usb]
extends = DFR1195_base
build_flags =
  ${DFR1195_base.build_flags}
  -I src/helpers/ui
  -I examples/companion_radio/ui-new
  -D DISPLAY_CLASS=DFR1195Display
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D OFFLINE_QUEUE_SIZE=256
build_src_filter =
  ${DFR1195_base.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<helpers/ui/ST7735Display.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<../examples/companion_radio/*.cpp>
  +<../examples/companion_radio/ui-new/*.cpp>
lib_deps =
  ${DFR1195_base.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:DFR1195_companion_radio_usb_no_lcd]
extends = DFR1195_base
build_flags =
  ${DFR1195_base.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D OFFLINE_QUEUE_SIZE=256
build_src_filter =
  ${DFR1195_base.build_src_filter}
  +<helpers/esp32/*.cpp>
  +<../examples/companion_radio/*.cpp>
lib_deps =
  ${DFR1195_base.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:DFR1195_room_server]
extends = DFR1195_base
build_src_filter =
  ${DFR1195_base.build_src_filter}
  +<helpers/ui/ST7735Display.cpp>
  +<../examples/simple_room_server>
build_flags =
  ${DFR1195_base.build_flags}
  -D DISPLAY_CLASS=DFR1195Display
  -D ADVERT_NAME='"DFR1195 Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
lib_deps =
  ${DFR1195_base.lib_deps}
  ${esp32_ota.lib_deps}

[env:DFR1195_room_server_no_lcd]
extends = DFR1195_base
build_src_filter =
  ${DFR1195_base.build_src_filter}
  +<../examples/simple_room_server>
build_flags =
  ${DFR1195_base.build_flags}
  -D ADVERT_NAME='"DFR1195 Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
lib_deps =
  ${DFR1195_base.lib_deps}
  ${esp32_ota.lib_deps}

[env:DFR1195_terminal_chat]
extends = DFR1195_base
build_flags =
  ${DFR1195_base.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
build_src_filter =
  ${DFR1195_base.build_src_filter}
  +<../examples/simple_secure_chat/main.cpp>
lib_deps =
  ${DFR1195_base.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:DFR1195_kiss_modem]
extends = DFR1195_base
build_src_filter =
  ${DFR1195_base.build_src_filter}
  +<../examples/kiss_modem/>
